export default [
    {
        Title: 'Comment 1',
        Content: 'Meaning of comment in English ... something that you say or write that expresses your opinion: I dont want any comments on/about my new haircut, thank you! He ...',
        CreateDate: '20-10-2021',
        Status: true,
        Resident: 'NGuyen Van A',
    },
    {
        Title: 'Comment 1',
        Content: 'Meaning of comment in English ... something that you say or write that expresses your opinion: I dont want any comments on/about my new haircut, thank you! He ...',
        CreateDate: '20-10-2021',
        Status: false,
        Resident: 'NGuyen Van A',
    },
    {
        Title: 'Comment 1',
        Content: 'Meaning of comment in English ... something that you say or write that expresses your opinion: I dont want any comments on/about my new haircut, thank you! He ...',
        CreateDate: '20-10-2021',
        Status: true,
        Resident: 'NGuyen Van A',
    },
    {
        Title: 'Comment 1',
        Content: 'Meaning of comment in English ... something that you say or write that expresses your opinion: I dont want any comments on/about my new haircut, thank you! He ...',
        CreateDate: '20-10-2021',
        Status: true,
        Resident: 'NGuyen Van A',
    },
    {
        Title: 'Comment 1',
        Content: 'Meaning of comment in English ... something that you say or write that expresses your opinion: I dont want any comments on/about my new haircut, thank you! He ...',
        CreateDate: '20-10-2021',
        Status: false,
        Resident: 'NGuyen Van A',
    },
    {
        Title: 'Comment 1',
        Content: 'Meaning of comment in English ... something that you say or write that expresses your opinion: I dont want any comments on/about my new haircut, thank you! He ...',
        CreateDate: '20-10-2021',
        Status: true,
        Resident: 'NGuyen Van A',
    },
    {
        Title: 'Comment 1',
        Content: 'Meaning of comment in English ... something that you say or write that expresses your opinion: I dont want any comments on/about my new haircut, thank you! He ...',
        CreateDate: '20-10-2021',
        Status: true,
        Resident: 'NGuyen Van A',
    },
    {
        Title: 'Comment 1',
        Content: 'Meaning of comment in English ... something that you say or write that expresses your opinion: I dont want any comments on/about my new haircut, thank you! He ...',
        CreateDate: '20-10-2021',
        Status: false,
        Resident: 'NGuyen Van A',
    },
    {
        Title: 'Comment 1',
        Content: 'Meaning of comment in English ... something that you say or write that expresses your opinion: I dont want any comments on/about my new haircut, thank you! He ...',
        CreateDate: '20-10-2021',
        Status: true,
        Resident: 'NGuyen Van A',
    },

]