export default [
    {
        Title: 'Post 1',
        Content: 'To prevent <b-modal> from closing (for example when validation fails). you can call the .preventDefault() method of the event object passed to your ok (OK button), cancel (Cancel button), close (modal header close button) and hide event handlers. Note that .preventDefault(), when used, must be called synchronously, as async is not supported',
        CreateDate: '20-10-2021',
        Status: true,
        Resident: 'NGuyen Van A',
    },
    {
        Title: 'Post 1',
        Content: 'To prevent <b-modal> from closing (for example when validation fails). you can call the .preventDefault() method of the event object passed to your ok (OK button), cancel (Cancel button), close (modal header close button) and hide event handlers. Note that .preventDefault(), when used, must be called synchronously, as async is not supported',
        CreateDate: '20-10-2021',
        Status: false,
        Resident: 'NGuyen Van A',
    },
    {
        Title: 'Post 1',
        Content: 'To prevent <b-modal> from closing (for example when validation fails). you can call the .preventDefault() method of the event object passed to your ok (OK button), cancel (Cancel button), close (modal header close button) and hide event handlers. Note that .preventDefault(), when used, must be called synchronously, as async is not supported',
        CreateDate: '20-10-2021',
        Status: true,
        Resident: 'NGuyen Van A',
    },
    {
        Title: 'Post 1',
        Content: 'To prevent <b-modal> from closing (for example when validation fails). you can call the .preventDefault() method of the event object passed to your ok (OK button), cancel (Cancel button), close (modal header close button) and hide event handlers. Note that .preventDefault(), when used, must be called synchronously, as async is not supported',
        CreateDate: '20-10-2021',
        Status: true,
        Resident: 'NGuyen Van A',
    },
    {
        Title: 'Post 1',
        Content: 'To prevent <b-modal> from closing (for example when validation fails). you can call the .preventDefault() method of the event object passed to your ok (OK button), cancel (Cancel button), close (modal header close button) and hide event handlers. Note that .preventDefault(), when used, must be called synchronously, as async is not supported',
        CreateDate: '20-10-2021',
        Status: true,
        Resident: 'NGuyen Van A',
    },
    {
        Title: 'Post 1',
        Content: 'To prevent <b-modal> from closing (for example when validation fails). you can call the .preventDefault() method of the event object passed to your ok (OK button), cancel (Cancel button), close (modal header close button) and hide event handlers. Note that .preventDefault(), when used, must be called synchronously, as async is not supported',
        CreateDate: '20-10-2021',
        Status: false,
        Resident: 'NGuyen Van A',
    },
    {
        Title: 'Post 1',
        Content: 'To prevent <b-modal> from closing (for example when validation fails). you can call the .preventDefault() method of the event object passed to your ok (OK button), cancel (Cancel button), close (modal header close button) and hide event handlers. Note that .preventDefault(), when used, must be called synchronously, as async is not supported',
        CreateDate: '20-10-2021',
        Status: true,
        Resident: 'NGuyen Van A',
    },
    {
        Title: 'Post 1',
        Content: 'To prevent <b-modal> from closing (for example when validation fails). you can call the .preventDefault() method of the event object passed to your ok (OK button), cancel (Cancel button), close (modal header close button) and hide event handlers. Note that .preventDefault(), when used, must be called synchronously, as async is not supported',
        CreateDate: '20-10-2021',
        Status: false,
        Resident: 'NGuyen Van A',
    },
    {
        Title: 'Post 1',
        Content: 'To prevent <b-modal> from closing (for example when validation fails). you can call the .preventDefault() method of the event object passed to your ok (OK button), cancel (Cancel button), close (modal header close button) and hide event handlers. Note that .preventDefault(), when used, must be called synchronously, as async is not supported',
        CreateDate: '20-10-2021',
        Status: false,
        Resident: 'NGuyen Van A',
    },
    {
        Title: 'Post 1',
        Content: 'To prevent <b-modal> from closing (for example when validation fails). you can call the .preventDefault() method of the event object passed to your ok (OK button), cancel (Cancel button), close (modal header close button) and hide event handlers. Note that .preventDefault(), when used, must be called synchronously, as async is not supported',
        CreateDate: '20-10-2021',
        Status: true,
        Resident: 'NGuyen Van A',
    },
    {
        Title: 'Post 1',
        Content: 'To prevent <b-modal> from closing (for example when validation fails). you can call the .preventDefault() method of the event object passed to your ok (OK button), cancel (Cancel button), close (modal header close button) and hide event handlers. Note that .preventDefault(), when used, must be called synchronously, as async is not supported',
        CreateDate: '20-10-2021',
        Status: true,
        Resident: 'NGuyen Van A',
    },

]